In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
plt.style.use('ggplot')

In [2]:
rmse_10=pd.DataFrame(columns=['time','pfRMSE','obsRMSE','Threat'])

In [7]:
df=pd.read_csv('500_0_pf.csv')
df

    ID    S    I  State  Nature  Obs
0    0  500    0      0       0    0
1    1  500    0      0       0    0
2    2  500    0      0       0    0
3    3  500    0      0       0    0
4    4  500    0      0       0    0
5    5    0  500      1       1    1
6    6  500    0      0       0    0
7    7  500    0      0       0    0
8    8  500    0      0       0    0
9    9  500    0      0       0    0
10  10  500    0      0       0    0
11  11  500    0      0       0    0
12  12  500    0      0       0    0
13  13  500    0      0       0    0
14  14  500    0      0       0    0
15  15  500    0      0       0    0
16  16  500    0      0       0    0
17  17  500    0      0       0    0
18  18  500    0      0       0    0
19  19  500    0      0       0    0
20  20  500    0      0       0    0
21  21  500    0      0       0    0
22  22  500    0      0       0    0
23  23  500    0      0       0    0
24  24  500    0      0       0    0
25  25  500    0      0       0    0
26  26  500    0      0       0    0
27  27  500    0      0       0    0
28  28  500    0      0       0    0
29  29  500    0      0       0    0
30  30  500    0      0       0    0
31  31  500    0      0       0    0
32  32  500    0      0       0    0
33  33  500    0      0       0    0
34  34  500    0      0       0    0
35  35  500    0      0       0    0
36  36  500    0      0       0    0
37  37  500    0      0       0    0
38  38  500    0      0       0    0
39  39  500    0      0       0    0